
server:
  port: 8888
spring:
# redis 配置
  redis:
    host: 112.74.115.69
    port: 6379
    password: tlx.123456
# 数据源配置
  datasource:
    druid:
      one:
        url: jdbc:mysql://112.74.115.69:3306/student?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
        username: root
        password: Tlx.123456
        driver-class-name: com.mysql.cj.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource
        initial-size: 4
        max-active: 8
        max-wait: 8
        validation-query-timeout: 10000
#       WebStatFilter配置，说明请参考Druid Wiki，配置_配置WebStatFilter
        web-stat-filter.enabled: true #是否启用StatFilter默认值false
#       StatViewServlet配置，说明请参考Druid Wiki，配置_StatViewServlet配置
        stat-view-servlet.enabled: true
        stat-view-servlet.login-username: dba
        stat-view-servlet.login-password: dba

      two:
        url: jdbc:mysql://127.0.0.1:3306/student?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=true
        username: root
        password: 123456
        driver-class-name: com.mysql.cj.jdbc.Driver
        type: com.alibaba.druid.pool.DruidDataSource
        initial-size: 4
        max-active: 8
        max-wait: 8
        validation-query-timeout: 10000
#       WebStatFilter配置，说明请参考Druid Wiki，配置_配置WebStatFilter
        web-stat-filter.enabled: true #是否启用StatFilter默认值false
#       StatViewServlet配置，说明请参考Druid Wiki，配置_StatViewServlet配置
        stat-view-servlet.enabled: true
        stat-view-servlet.login-username: dba
        stat-view-servlet.login-password: dba
